### ISSUE TITLE
docker images

### ISSUE THREAD

**Issue by danielraq** [rhasspy/wyoming-satellite#147]
Hi 
Is there a possibility that you will provide docker images? It would be much easier to work with them.
Will this installation work on ordinary linux system like ubuntu? 
Did you tested the app with bluetooth speakerphones?

**Comment by TimP4w** [comment]
You can fork the repo and create your own pipelines to generate an image (on github, if you leave them public it's going to be free). 
But you also don't really need them, because with docker-compose you can define a build URL that does that for you.

See my `docker-compose.yml`

<details>
  <summary>docker-compose.yml</summary>

```yaml

version: "3.8"
services:
  playback:
    container_name: wyoming-snd-external
    build: https://github.com/rhasspy/wyoming-snd-external.git
    image: wyoming-snd-external
    restart: unless-stopped
    ports:
      - "10601:10601"
    devices:
      - /dev/snd:/dev/snd
    group_add:
      - audio
    command:
      - "--device"
      - "plughw:CARD=Headphones"
      - "--debug"
  microphone:
    container_name: wyoming-mic-external
    build: https://github.com/rhasspy/wyoming-mic-external.git
    image: wyoming-mic-external
    restart: unless-stopped
    ports:
      - "10600:10600"
    devices:
      - /dev/snd:/dev/snd
    group_add:
      - audio
    depends_on:
      - satellite
    command:
      - "--device"
      - "plughw:CARD=seeed4micvoicec"
      - "--debug"
  satellite:
    container_name: wyoming-satellite
    build: https://github.com/rhasspy/wyoming-satellite.git
    image: wyoming-satellite
    hostname: jarvis-satellite
    restart: unless-stopped
    ports:
      - "10700:10700"
    command:
      - "--name"
      - "jarvis-satellite"
      - "--uri"
      - "tcp://0.0.0.0:10700"
      - "--mic-uri"
      - "tcp://microphone:10600"
      - "--snd-uri"
      - "tcp://playback:10601"
      - "--wake-uri"
      - "tcp://openwakeword:10400"
      - "--wake-word-name" 
      - "hey_jarvis"
      - "--event-uri"
      - "tcp://event-handler:10500"
      - "--debug"
  openwakeword:
    image: "rhasspy/wyoming-openwakeword"
    restart: always
    ports:
      - "10400:10400"
    command:
      - "--preload-model"
      - "hey_jarvis"

  ```
</details>

You can then just run `docker-compose up --build`.

For bluetooth my guess is that you could just pass that device and would work.
