### ISSUE TITLE
Local Wakeword Detection not working 

### ISSUE THREAD

**Issue by sebirdman** [rhasspy/wyoming-satellite#16]
I'm running a Raspberry Pi 4 with openwakeword. 

As soon as i add the options 

```
      - "tcp://openwakeword:10400"
      - "--wake-word"
      - "ok_nabu"
```

to my docker container config the wakeword detection stops working. 

If i remove it and use the remote one on the server, all is fine. 

here's my docker config for these:

```
services:
  satellite:
    container_name: satellite
    depends_on:
      - openwakeword
    build:
      context: ./satellite/wyoming-satellite
      dockerfile: Dockerfile
    ports:
      - "10700:10700"
    devices:
      - /dev/snd:/dev/snd
    environment:
      - "PULSE_SERVER=tcp:10.0.1.243:4713"
    restart: unless-stopped
    command:
      - "--name"
      - "my satellite"
      - "--uri"
      - "tcp://0.0.0.0:10700"
      - "--mic-command"
      - "arecord -D plughw:CARD=OSM09,DEV=0 -r 16000 -c 1 -f S16_LE -t raw"
      - "--snd-command"
      - "paplay --device=alsa_output.platform-soc_sound.stereo-fallback --format=s16le --rate=22050 --channels=1 --raw"
      - "--awake-wav"
      - "./sounds/awake.wav"
      - "--detection-command"
      - "./get_loopback.sh module-loopback.c 0%"
      - "--tts-stop-command"
      - "./get_loopback.sh module-loopback.c 100%"
      - "--wake-uri"
      - "tcp://openwakeword:10400"
      - "--wake-word"
      - "ok_nabu"
      - "--debug"
      
openwakeword:
    container_name: openwakeword
    image: rhasspy/wyoming-openwakeword
    volumes:
      - ./wakeword/config:/data
      - ./wakeword/config:/custom
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=America/Los_Angeles
    command: --preload-model "ok_nabu" --debug
    restart: unless-stopped
    expose:
      - 10400/tcp
 ```
