### ISSUE TITLE
Play TTS sound on Home Assistant media_player

### ISSUE THREAD

**Issue by ElVit** [rhasspy/wyoming-satellite#18]
Hi,
Is it already possible to play the tts sound on a home assistant media_player entity?

I saw something similar [here](https://community.home-assistant.io/t/esphome-voice-assistant-speech-output-to-home-assistant-media-player/588337/11?u=elvit) for the ESPHome Voice Assistant. 
I have a Sonos One added to home assistant and would like to play the tts sound there.

**Comment by HarvsG** [comment]
Related forum post with 60 upvotes: https://community.home-assistant.io/t/voice-assistant-have-assistant-reply-on-a-different-media-player/625875

**Comment by ElVit** [comment]
Thanks for your link. 
I voted also for this feature request now.
Unfortunatelly I could not find a solution in the comments for the wyoming-statellite.
But I will keep watching also the home assistant community posts.

**Comment by gafk** [comment]
I am using a workaround by calling the tts.cloud_say service through the HA API and passing the text:

Modify the script synthesize.sh in examples/commands/ like this:
```
#!/usr/bin/env sh

text="$(cat)"
echo "Text to speech text: ${text}"
curl \
  -H "Authorization: Bearer YOUR_API_TOKEN
  -H "Content-Type: application/json" \
  -d '{"entity_id": "media_player.YOUR_ENTITY_ID", "message": "'"${text}"'"}' \
  http://192.168.XXX.XXX:8123/api/services/tts/cloud_say
```

Add this to the script/run command:
```
--synthesize-command examples/commands/synthesize.sh
```

I am using cloud TTS, but should also work with any other tts service that you are using.

**Comment by ElVit** [comment]
Thanks for your help @gafk.
It worked also for me. 
I used the `tts.piper` services and this is my `synthesize.sh` file:
```
#!/usr/bin/env sh

text="$(cat)"
echo "Text to speech text: ${text}"

token='abcdefghijklmnopqrstuvwxyz12345567890'
echo "${token}"

curlData='{
  "entity_id": "tts.piper",
  "media_player_entity_id": "media_player.sonos_one",
  "message": "'$text'"
}';
echo "$curlData" | jq '.'

curl \
  -X POST \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $token" \
  -d "$curlData" \
  http://192.168.1.1:8123/api/services/tts/speak
```

**Comment by ElVit** [comment]
For completeness here my `detection.sh` file:

```
#!/usr/bin/env sh

name="$(cat)"
echo "Wake word detected: ${name}"

token='abc123'
echo "${token}"

data='{
  "entity_id": "media_player.sonos_one",
  "media_content_type": "music",
  "media_content_id": "media-source://media_source/local/sounds/done.wav"
}';
echo "${data}" | jq '.'

curl \
 -X POST \
 -H "Content-Type: application/json" \
 -H "Authorization: Bearer $token" \
 -d "$data" \
  http://192.168.1.1:8123/api/services/media_player/play_media
```

My Sonos One will then play a sound when the wake word is detected. 
The `done.wav` file is located here:
`/media/sounds/done.wav`

**Comment by HarvsG** [comment]
Can you also share your service ini file, or at least the line that calls the command with all the flags

**Comment by ElVit** [comment]
Yes sure. 
I followed the tutorial from the docs directory of this repo and created the file `wyoming-satellite.service`. 
This is it's content:

```
[Unit]
Description=Wyoming Satellite
Wants=network-online.target
After=network-online.target

[Service]
Type=simple
ExecStart=/home/pi/wyoming-satellite/script/run \
  --name 'rpi3-satellite' \
  --uri 'tcp://0.0.0.0:10700' \
  --mic-command 'arecord -D plughw:CARD=CameraB409241,DEV=0 -r 16000 -c 1 -f S16_LE -t raw' \
  --snd-command 'aplay -D default -r 22050 -c 1 -f S16_LE -t raw' \
  --synthesize-command 'examples/commands/synthesize.sh' \
  --detection-command 'examples/commands/detection.sh'
WorkingDirectory=/home/pi/wyoming-satellite
Restart=always
RestartSec=1

[Install]
WantedBy=default.target
```

**Comment by ElVit** [comment]
I use a Raspberry Pi 3 B with an PS3 Eye Camera. It was quite easy to setup. There is no need to install any additional drivers. 

![image](https://github.com/rhasspy/wyoming-satellite/assets/54866762/6587dc9c-2191-4fc1-b0cd-a91fd0fb4b02)

**Comment by HA-TB303** [comment]
Hi, tried this and I am not getting any sound from the (google home or sonos speaker)

Tried:
- Create a Long-lived access token in HA
-  edited: sudo nano wyoming-satellite/examples/commands/synthesize.sh 
Contents:
```
#!/usr/bin/env sh

text="$(cat)"
echo "Text to speech text: ${text}"

token='MY_VERY_LONG_TOKEN'
echo "${token}"

curlData='{
  "entity_id": "tts.edge_tts",
  "media_player_entity_id": "media_player.cast_google_nest_kantoor",
  "message": "'$text'"
}';
echo "$curlData" | jq '.'

curl \
  -X POST \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $token" \
  -d "$curlData" \
  http://192.168.207.101:8123/api/services/tts/speak
```

- edited: sudo systemctl edit --force --full wyoming-satellite.service
Contents:
```
  GNU nano 5.4                                                                                 /etc/systemd/system/.#wyoming-satellite.service9267e9f55b280f59                                                                                           
[Unit]
Description=Wyoming Satellite
Wants=network-online.target
After=network-online.target
Requires=wyoming-openwakeword.service
Requires=2mic_leds.service

[Service]
Type=simple
ExecStart=/home/pi/wyoming-satellite/script/run \
        --name 'whysat-02' \
        --uri 'tcp://0.0.0.0:10700' \
        --mic-command 'arecord -D plughw:CARD=seeed2micvoicec,DEV=0 -r 16000 -c 1 -f S16_LE -t raw' \
        --snd-command 'aplay -D plughw:CARD=seeed2micvoicec,DEV=0 -r 16000 -c 1 -f S16_LE -t raw' \
        --snd-command-rate 16000 \
        --snd-volume-multiplier 1.0 \
        --synthesize-command 'examples/commands/synthesize.sh' \
#       --detection-command 'examples/commands/detection.sh' \
        --wake-uri 'tcp://127.0.0.1:10400' \
        --wake-word-name 'hey_jarvis' \
        --event-uri 'tcp://127.0.0.1:10500' \
        --awake-wav sounds/awake.wav \
        --done-wav sounds/done.wav
WorkingDirectory=/home/pi/wyoming-satellite
Restart=always
RestartSec=1

[Install]
WantedBy=default.target
```

Logs:

```
==> /var/log/syslog <==
Feb  4 17:42:30 whysat-02 run[2670]: INFO:root:Waiting for wake word
Feb  4 17:42:30 whysat-02 run[2679]: Playing raw data 'stdin' : Signed 16 bit Little Endian, Rate 16000 Hz, Mono

==> /var/log/daemon.log <==
Feb  4 17:42:34 whysat-02 run[2682]: Text to speech text: Het licht in het kantoor is ingeschakeld.
Feb  4 17:42:34 whysat-02 run[2682]: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJjNmI1MDNlZDMxYjI0ZDViYmRiMTVmYjM1ZWZlNjc1MCIsImlhdCI6MTcwNzA2MzM3NSwiZXhwIjoyMDIyNDIzMzc1fQ.NF0Ma6KvyVgDzAJngVrGVZzvaxoWgWkpXSN_3_VsUGU

==> /var/log/syslog <==
Feb  4 17:42:34 whysat-02 run[2682]: Text to speech text: Het licht in het kantoor is ingeschakeld.
Feb  4 17:42:34 whysat-02 run[2682]: MY_VERY_LONG_TOKEN

==> /var/log/daemon.log <==
Feb  4 17:42:34 whysat-02 run[2686]: {
Feb  4 17:42:34 whysat-02 run[2686]:   "entity_id": "tts.edge_tts",
Feb  4 17:42:34 whysat-02 run[2686]:   "media_player_entity_id": "media_player.cast_google_nest_kantoor",
Feb  4 17:42:34 whysat-02 run[2686]:   "message": "Het licht in het kantoor is ingeschakeld."
Feb  4 17:42:34 whysat-02 run[2686]: }
Feb  4 17:42:34 whysat-02 run[2687]:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Feb  4 17:42:34 whysat-02 run[2687]:                                  Dload  Upload   Total   Spent    Left  Speed
Feb  4 17:42:35 whysat-02 run[2687]: #015  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0#015100   162  100     2  100   160    100   8000 --:--:-- --:--:-- --:--:--  8526
Feb  4 17:42:35 whysat-02 run[2687]: []
Feb  4 17:42:35 whysat-02 run[2688]: Playing raw data 'stdin' : Signed 16 bit Little Endian, Rate 16000 Hz, Mono

==> /var/log/syslog <==
Feb  4 17:42:34 whysat-02 run[2686]: {
Feb  4 17:42:34 whysat-02 run[2686]:   "entity_id": "tts.edge_tts",
Feb  4 17:42:34 whysat-02 run[2686]:   "media_player_entity_id": "media_player.cast_google_nest_kantoor",
Feb  4 17:42:34 whysat-02 run[2686]:   "message": "Het licht in het kantoor is ingeschakeld."
Feb  4 17:42:34 whysat-02 run[2686]: }
Feb  4 17:42:34 whysat-02 run[2687]:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Feb  4 17:42:34 whysat-02 run[2687]:                                  Dload  Upload   Total   Spent    Left  Speed
Feb  4 17:42:35 whysat-02 run[2687]: #015  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0#015100   162  100     2  100   160    100   8000 --:--:-- --:--:-- --:--:--  8526
Feb  4 17:42:35 whysat-02 run[2687]: []
Feb  4 17:42:35 whysat-02 run[2688]: Playing raw data 'stdin' : Signed 16 bit Little Endian, Rate 16000 Hz, Mono
```

**Comment by HA-TB303** [comment]
I also tried tts.cloud_say and changing the HA url from:

http://192.168.207.101:8123/api/services/tts/speak

to:

http://192.168.207.101:8123/api/services/tts/cloud_say

But then I do get an error in the logs.

**Comment by ElVit** [comment]
The service call is different for edge_tts. You can see the structure in the developer tools if you choose the service `tts.edge_tts_say`. 

I didn't tried it but your synthesize.sh should look like this:
```
#!/usr/bin/env sh

text="$(cat)"
echo "Text to speech text: ${text}"

token='MY_VERY_LONG_TOKEN'
echo "${token}"

curlData='{
  "entity_id": "media_player.cast_google_nest_kantoor",
  "message": "'$text'"
}';
echo "$curlData" | jq '.'

curl \
  -X POST \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $token" \
  -d "$curlData" \
  http://192.168.207.101:8123/api/services/tts/edge_tts_say
```

**Comment by HA-TB303** [comment]
Hi, I see this differs from your previous example...

```
curlData='{
  "entity_id": "tts.edge_tts",
  "media_player_entity_id": "media_player.cast_google_nest_kantoor",
  "message": "'$text'"
}';
```
Sadly this does not work either. I get the same error I got as to when I tried cloud_tts before...
```
==> /var/log/syslog <==
Feb  4 20:46:04 whysat-02 run[768]: {
Feb  4 20:46:04 whysat-02 run[768]:   "entity_id": "media_player.cast_google_nest_kantoor",
Feb  4 20:46:04 whysat-02 run[768]:   "message": "Het licht in het kantoor is ingeschakeld."
Feb  4 20:46:04 whysat-02 run[768]: }
Feb  4 20:46:04 whysat-02 run[769]:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Feb  4 20:46:04 whysat-02 run[769]:                                  Dload  Upload   Total   Spent    Left  Speed
Feb  4 20:46:04 whysat-02 run[769]: #015  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0#015100   132  100    16  100   116   2285  16571 --:--:-- --:--:-- --:--:-- 18857
Feb  4 20:46:04 whysat-02 run[769]: 400: Bad Request
Feb  4 20:46:04 whysat-02 run[770]: Playing raw data 'stdin' : Signed 16 bit Little Endian, Rate 16000 Hz, Mono
```

Config:
```                                                                                         
#!/usr/bin/env sh

text="$(cat)"
echo "Text to speech text: ${text}"

token='XXXXXXXXXXXXXXXXXXXX'
echo "${token}"

curlData='{
  "entity_id": "media_player.cast_google_nest_kantoor",
  "message": "'$text'"
}';
echo "$curlData" | jq '.'

curl \
  -X POST \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $token" \
  -d "$curlData" \
  http://192.168.207.101:8123/api/services/tts/edge_tts_say
```

**Comment by HA-TB303** [comment]
When doing it manually:
```
pi@whysat-02:~ $ curl \
  -X POST \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer XXXXXXXXXXXXX" \
  -d '{"entity_id": "media_player.cast_google_nest_kantoor", "message": "Test."}' \
  http://192.168.207.101:8123/api/services/tts/edge_tts_say

400: Bad Requestpi@whysat-02:~ $ 
```

**Comment by HA-TB303** [comment]
That put me on the right track:

This does work:
```
pi@whysat-02:~ $ curl \
  -X POST \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer XXXXXXXXXXXXX" \
  -d '{"entity_id": "media_player.cast_google_nest_kantoor", "message": "Test."}' \
  http://192.168.207.101:8123/api/services/tts/cloud_say

400: Bad Requestpi@whysat-02:~ $
```

I have the synthesis.sh working now also :)

**Comment by HA-TB303** [comment]
Great stuff. Is there a way to keep the sonos speaker muted until the assist-instructions have been issued?

I notice that the music from the sonos interferes with the voice instruction given to the pi. The pi is having a hard time understanding the instructions.

**Comment by sebastianfurth** [comment]
Hi @HA-TB303, 

would you mind sharing your working synthesize.sh here? 

Thanks!

**Comment by HA-TB303** [comment]
sure:

```
#!/usr/bin/env sh

text="$(cat)"
echo "Text to speech text: ${text}"

token='LONGTOKEN'
echo "${token}"

curlData='{
  "entity_id": "media_player.cast_google_nest_kantoor",
  "message": "'$text'"
}';
echo "$curlData" | jq '.'

curl \
  -X POST \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $token" \
  -d "$curlData" \
  http://192.168.207.101:8123/api/services/tts/cloud_say

```

**Comment by evgenyyy** [comment]
I also implemented this and it works for shorter responses but it doesn't work when the TTS response is a few sentences (I use OpenAI pipeline). 

The error is `parse error: Invalid string: control characters from U+0000 through U+001F must be escaped`

Seems like jq doesn't like new lines but I have no idea how to solve it...

**Comment by tombul** [comment]
first things first: **thank you all very much**! 

the way with the shell scripts that excecute whatever code works perfectly (for me). <3 
i just call a script inside home assistant which i then adapt to my needs.

but i do seem to run into the same issue @evgenyyy is encountering. if i use openai as a conversation agent and got a long response i get `WARNING:root:Did not receive ping response within timeout
INFO:root:Disconnected from server`. according to https://github.com/rhasspy/wyoming-satellite/issues/59 this was recently introduced.
for now i am still looking for a way to just ignore the ping, as i know my stuff works and it currently is talking - after finishing a long reply it does even send back everthing.
but it seems that --connection-timeout/-m/--max-time doe not help or the ping does not stem from the curl command.

regarding @HA-TB303 input relating to sonos interfering with the voice recognition. i solved this by using the detection.sh for setting the volume level of the corresponding sonos to 0.05 and set it back in stt_stop.sh. this works like a charm. only thing i need to figure out is how to give voice output before the voice recognition starts. (like "how can i be of help?" or similar)

**Comment by HA-TB303** [comment]
> first things first: **thank you all very much**!
> 
> the way with the shell scripts that excecute whatever code works perfectly (for me). <3 i just call a script inside home assistant which i then adapt to my needs.
> 
> but i do seem to run into the same issue @evgenyyy is encountering. if i use openai as a conversation agent and got a long response i get `WARNING:root:Did not receive ping response within timeout INFO:root:Disconnected from server`. according to #59 this was recently introduced. for now i am still looking for a way to just ignore the ping, as i know my stuff works and it currently is talking - after finishing a long reply it does even send back everthing. but it seems that --connection-timeout/-m/--max-time doe not help or the ping does not stem from the curl command. my text gets read out correctly, just fyi. i use media_player.play and give the openai ersult into the media_content_id like `media_content_id: >- media-source://tts/cloud?message="{{ message | replace(' ', '+') }}"&language=en-CA&voice=LiamNeural`
> 
> regarding @HA-TB303 input relating to sonos interfering with the voice recognition. i solved this by using the detection.sh for setting the volume level of the corresponding sonos to 0.05 and set it back in stt_stop.sh. this works like a charm. only thing i need to figure out is how to give voice output before the voice recognition starts. (like "how can i be of help?" or similar)

Great idea! Would you mind sharing your configs?

**Comment by tombul** [comment]
sure. sorry for the wall of text, i thought i provide every file and script that is called, just in case someone finds it helpful.

my wyoming-setellite.service:
```shell
[Unit]
Description=Wyoming Satellite
Wants=network-online.target
After=network-online.target
Requires=wyoming-openwakeword.service
Requires=4mic_leds.service

[Service]
Type=simple
ExecStart=/home/livingroomsatellite/wyoming-satellite/script/run \
        --name 'Living Room Satellite' \
        --uri 'tcp://0.0.0.0:10700' \
        --mic-command 'arecord -D plughw:CARD=seeed4micvoicec,DEV=0 -r 16000 -c 1 -f S16_LE -t raw' \
        --snd-command 'aplay -D plughw:CARD=vc4hdmi,DEV=0 -r 16000 -c 1 -f S16_LE -t raw'  \
        --snd-command-rate 16000 \
        --snd-volume-multiplier 1.0 \
        --mic-auto-gain 5 \
        --mic-noise-suppression 2 \
        --wake-uri 'tcp://127.0.0.1:10400' \
        --wake-word-name 'hey_jarvis' \
        --event-uri 'tcp://127.0.0.1:10500' \
        --synthesize-command 'examples/commands/synthesize.sh' \
        --detection-command 'examples/commands/detection.sh' \
        --stt-stop-command 'examples/commands/stt_stop.sh'
WorkingDirectory=/home/livingroomsatellite/wyoming-satellite
Restart=always
RestartSec=1
``` 

in home assistant i am calling a script called announce_detection and announce_detection_end which themselves call scripts that save the current volume level and set a new one and later reset the volume to the previously saved value.
i do that, because i want to mute the voice output at night(via test if the sun is between rising and setting) and not always have to connect to the satellite to change minor stuff. it's quite convenient and offers a lot of possibilities.

first for detection.sh, i call that with target living room sonos and with volume level 0.05 - which saves the previous volume level in the helper variable input_number.previous_volume:
```python
sequence:
  - if:
      - condition: template
        value_template: is_state({{target}}, 'off')
    then:
      - service: media_player.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: "{{target}}"
    else:
      - service: input_number.set_value
        data:
          value: |
            {{ state_attr(target,'volume_level') }}
        target:
          entity_id: input_number.previous_volume
    enabled: true
  - service: media_player.volume_set
    metadata: {}
    data:
      volume_level: "{{volume_level | float}}"
    target:
      entity_id: "{{target}}"
    enabled: true
fields:
  target:
    selector:
      entity:
        filter:
          - integration: sonos
            domain: media_player
        multiple: false
    name: target
    description: The target speaker for which to set the volume.
    required: true
  volume_level:
    selector:
      number:
        min: 0
        max: 1
        step: 0.01
    name: volume level
    description: The volume level to which to adjust the speaker to. Defaults to 0.25.
    default: 0.25
mode: single
``` 

and in stt_stop.sh i call the following script, again for the sonos in my living room:
```python
sequence:
  - service: media_player.volume_set
    metadata: {}
    data:
      volume_level: "{{states('input_number.previous_volume') | float}}"
    target:
      entity_id: "{{target}}"
fields:
  target:
    selector:
      entity:
        filter:
          - integration: sonos
            domain: media_player
        multiple: false
    name: target
    description: The target speaker for which to set the volume.
    required: true
mode: single
``` 

and my announce_jarvis calls the scripts to save the current volume level, set a new one, then the following media_player.play_media and then it resets the volume level again. @evgenyyy i changed my string-replace to urlencode and that seems to work fine too. now it doesn't stop when encountering stuff like '#' at least.
```python
service: media_player.play_media
target:
  entity_id: "{{ target }}"
data:
  media_content_id: >-
    media-source://tts/cloud?message="{{ message | urlencode
    }}"&language=en-CA&voice=LiamNeural
  media_content_type: provider
  announce: true
metadata:
  title: "{{message}}"
  thumbnail: https://brands.home-assistant.io/_/cloud/logo.png
  media_class: app
  children_media_class: null
  navigateIds:
    - {}
    - media_content_type: app
      media_content_id: media-source://tts
    - media_content_type: provider
      media_content_id: >-
        media-source://tts/cloud?message="{{ message | urlencode
        }}"&language=en-CA&voice=LiamNeural

``` 

for completions sake, my .sh files:
my detection.sh:
```shell
#!/usr/bin/env sh

name="$(cat)"
echo "Wake word detected: ${name}"

token='longtokengeneratedinhomeassistant'

curlData='{
  "target": "media_player.wohnzimmer"
}';
echo "$curlData" | jq '.'

curl \
  -X POST \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $token" \
  -d "$curlData" \
  http://192.168.0.131:8123/api/services/script/announce_jarvis_detection
``` 

my stt_stop.sh:
```shell
#!/usr/bin/env sh

echo 'User has stopped speaking'

token='longtokengeneratedinhomeassistant'

curlData='{
  "target": "media_player.wohnzimmer"
}';
echo "$curlData" | jq '.'

curl \
  -X POST \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $token" \
  -d "$curlData" \
  http://192.168.0.131:8123/api/services/script/announce_jarvis_detection_end
``` 

my synthezise.sh:
```shell
#!/usr/bin/env sh

text="$(cat)"
echo "Text to speech text: ${text}"

token='longtokengeneratedinhomeassistant'

curlData='{
  "volume_level": 0.4,
  "target": "media_player.wohnzimmer",
  "message": "'$text'"
}';
echo "$curlData" | jq '.'

curl \
  -X POST \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $token" \
  -d "$curlData" \
  http://192.168.0.131:8123/api/services/script/announce_jarvis
```

**Comment by HA-TB303** [comment]
Hi, Thanks for sharing.

I just can't get the following scripts working in Home Assistant. If I reload HA I do not get any errors, but the script services do not appear. Are you sure the syntax is correct?

 anounce_jarvis_detection
 anounce_jarvis_detection_end
 anounce_jarvis

**Comment by tombul** [comment]
hey there. yes, that is how i named them.

but you can name them how you like, that is just the name of the script in home assistant:
![Screenshot 2024-02-15 172844](https://github.com/rhasspy/wyoming-satellite/assets/1674633/bb5cb545-1ca2-4fef-b9e7-b6b4853325cc)
in that script you just do whatever you want and at the end home assistant will respond to your satellite, which will receive a huge payload that will be printed to your log and visible via `journalctl -u wyoming-satellite.service -f`.

does yout satellite send a request to home assistant? if so, you should see something with the above command.
some example output from a synthesize output, with the response that shows that announce jarvis was called:
<details><summary>log output of synthesize call</summary>
<p>

voicesatellite run[1115]: {
voicesatellite run[1115]:   "volume_level": 0.4,
voicesatellite run[1115]:   "target": "media_player.wohnzimmer",
voicesatellite run[1115]:   "message": "Turned off the light"
voicesatellite run[1115]: }
voicesatellite run[1117]:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
voicesatellite run[1117]:                                  Dload  Upload   Total   Spent    Left  Speed
voicesatellite run[1117]: [316B blob data]
voicesatellite run[1117]: [{"entity_id":"script.announce_jarvis", a whole lot of ids, states and other stuff }]

</p>
</details>

**Comment by HA-TB303** [comment]
The issues is within Home Assistant. If I add your scripts to my jarvis_package.yaml, they won't work. I do not seem them in the services, I do see other scripts. I do not see any errors in the logs, but it must be syntax or formatting related.

Can you share the full syntax from your scripts.yaml of configuration.yaml file?

**Comment by HA-TB303** [comment]
This is my jarvis_package.yaml

```
input_number:
  previous_volume:
    initial: 0.5
    
script:
  anounce_jarvis_detection:
    alias: anounce_jarvis_detection
    sequence:
    - if:
      - condition: template
        value_template: is_state({{target}}, 'off')
      then:
      - service: media_player.turn_on
        target:
          entity_id: '{{target}}'
      else:
      - service: input_number.set_value
        data:
          value: '{{ state_attr(target,''volume_level'') }}'
        target:
          entity_id: input_number.previous_volume
      enabled: true
    - service: media_player.volume_set
      data:
        volume_level: 0.05
      target:
        entity_id: '{{target}}'
      enabled: true
    fields:
      target:
        selector:
          entity:
            filter:
            - integration: sonos
              domain: media_player
            multiple: false
        name: target
        description: The target speaker for which to set the volume.
        required: true
    mode: single
  anounce_jarvis_detection_end:
    alias: anounce_jarvis_detection_end
    sequence:
    - service: media_player.volume_set
      data:
        volume_level: '{{states(''input_number.previous_volume'') | float}}'
      target:
        entity_id: '{{target}}'
    fields:
      target:
        selector:
          entity:
            filter:
            - integration: sonos
              domain: media_player
            multiple: false
        name: target
        description: The target speaker for which to set the volume.
        required: true
    mode: single
  anounce_jarvis:
    alias: announce_jarvis
    sequence:
      service: media_player.play_media
      target:
        entity_id: '{{ target }}'
      data:
        media_content_id: media-source://tts/cloud?message="{{ message | urlencode }}"&language=en-CA&voice=LiamNeural
        media_content_type: provider
        announce: true
      metadata:
        title: '{{message}}'
        thumbnail: https://brands.home-assistant.io/_/cloud/logo.png
        media_class: app
        children_media_class:
        navigateIds:
        - media_content_type: app
          media_content_id: media-source://tts
        - media_content_type: provider
          media_content_id: media-source://tts/cloud?message="{{ message | urlencode}}"&language=en-CA&voice=LiamNeural
```

I feel like I am overlooking something here....

**Comment by HA-TB303** [comment]
It works. Total picnic issue on my side :(

**Comment by HA-TB303** [comment]
When I send:
```
curl \
  -X POST \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer TOKEN" \
  -d '{"entity_id": "media_player.sonos_arc_woonkamer", "message": "Test."}' \
  http://192.168.207.101:8123/api/services/tts/cloud_say
```

I get ' test'

When sending:

```
curl \
  -X POST \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer TOKEN" \
  -d '{"entity_id": "media_player.sonos_arc_woonkamer", "message": "Test."}' \
  http://192.168.0.131:8123/api/services/script/announce_jarvis
```
Nothing happens

**Comment by HA-TB303** [comment]
Could you please edit your script in YAML and send me the entire script as you use it?

![CleanShot 2024-02-15 at 18 39 59](https://github.com/rhasspy/wyoming-satellite/assets/9609805/98d6ee3e-3e77-413a-acd3-3bcd0582b2da)

**Comment by HA-TB303** [comment]
For more debugging i ran your script using the actual data in stead of the variables passed by the whyoming satellite script and then it works, so the script in HA works.

```
  anounce_jarvis:
    alias: announce_jarvis
    sequence:
      service: media_player.play_media
      target:
        entity_id: media_player.sonos_arc_woonkamer
      data:
        media_content_id: media-source://tts/cloud?message="this is a test"&language=en-CA&voice=LiamNeural
        media_content_type: provider
        announce: true
      metadata:
        title: TEST
        thumbnail: https://brands.home-assistant.io/_/cloud/logo.png
        media_class: app
        children_media_class:
        navigateIds:
        - media_content_type: app
          media_content_id: media-source://tts
        - media_content_type: provider
          media_content_id: media-source://tts/cloud?message="This is a test"&language=en-CA&voice=LiamNeural
```

Somehow it is not calling the script correctly.

**Comment by HA-TB303** [comment]
For full context my config and scripts:

wyoming-satellite.service
```
[Unit]
Description=Wyoming Satellite
Wants=network-online.target
After=network-online.target
Requires=wyoming-openwakeword.service
Requires=2mic_leds.service

[Service]
Type=simple
ExecStart=/home/pi/wyoming-satellite/script/run \
        --name 'whysat-02' \
        --uri 'tcp://0.0.0.0:10700' \
        --mic-command 'arecord -D plughw:CARD=seeed2micvoicec,DEV=0 -r 16000 -c 1 -f S16_LE -t raw' \
        --snd-command 'aplay -D plughw:CARD=seeed2micvoicec,DEV=0 -r 16000 -c 1 -f S16_LE -t raw' \
        --snd-command-rate 16000 \
        --snd-volume-multiplier 1.0 \
        --mic-auto-gain 5 \
        --mic-noise-suppression 2 \
        --wake-uri 'tcp://127.0.0.1:10400' \
        --wake-word-name 'hey_jarvis' \
        --synthesize-command 'examples/commands/synthesize.sh' \
        --detection-command 'examples/commands/detection.sh' \
        --stt-stop-command 'examples/commands/stt_stop.sh' \
        --event-uri 'tcp://127.0.0.1:10500' \
        --awake-wav sounds/awake.wav \
        --done-wav sounds/done.wav
WorkingDirectory=/home/pi/wyoming-satellite
Restart=always
RestartSec=1
```

wyoming-satellite/examples/commands/synthesize.sh                                                                                                      
```
#!/usr/bin/env sh

text="$(cat)"
echo "Text to speech text: ${text}"

token='TOKEN'

curlData='{
  "volume_level": 0.4,
  "target": "media_player.sonos_arc_woonkamer",
  "message": "'$text'"
}';
echo "$curlData" | jq '.'

curl \
  -X POST \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $token" \
  -d "$curlData" \
  http://192.168.207.101:8123/api/services/script/announce_jarvis
```

wyoming-satellite/examples/commands/detection.sh 
```
#!/usr/bin/env sh

name="$(cat)"
echo "Wake word detected: ${name}"

token='TOKEN'

curlData='{
  "target": "media_player.sonos_arc_woonkamer"
}';
echo "$curlData" | jq '.'

curl \
  -X POST \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $token" \
  -d "$curlData" \
  http://192.168.207.101:8123/api/services/script/announce_jarvis_detection
```

wyoming-satellite/examples/commands/stt_stop.sh                                                                                                       
```
#!/usr/bin/env sh

echo 'User has stopped speaking'

token='TOKEN'

curlData='{
  "target": "media_player.sonos_arc_woonkamer"
}';
echo "$curlData" | jq '.'

curl \
  -X POST \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $token" \
  -d "$curlData" \
  http://192.168.207.101:8123/api/services/script/announce_jarvis_detection_end
```

**Comment by tombul** [comment]
hm, as far as i can see, assuming your token and home assistant ip are correct, it seems correct to me. no mistakes i can spot.

have you tried calling another script, that does not need parameters and just executes stuff? just to be sure the parameters are not the cause of it and you can call custom scripts? no other ideas on my end for now

**Comment by HA-TB303** [comment]
Thanks, it was the script naming. I had to put them in the config exactly like this:
```
script:
  'announce_jarvis':
    alias: announce_jarvis
    sequence:
    - service: media_player.play_media
      target:
        entity_id: '{{target}}'
      data:
        media_content_id: media-source://tts/cloud?message="{{ message | urlencode }}"&language=nl-NL&voice=ColetteNeural
        media_content_type: provider
        announce: true
      metadata:
        title: '{{message}}'
        thumbnail: https://brands.home-assistant.io/_/cloud/logo.png
        media_class: app
        children_media_class:
        navigateIds:
        - media_content_type: app
          media_content_id: media-source://tts
        - media_content_type: provider
          media_content_id: media-source://tts/cloud?message="{{ message | urlencode}}"&language=nl-NL&voice=ColetteNeural
    mode: single
  'announce_jarvis_detection':
    alias: announce_jarvis_detection
    sequence:
    - if:
      - condition: template
        value_template: is_state({{target}}, 'off')
      then:
      - service: media_player.turn_on
        target:
          entity_id: '{{target}}'
      else:
      - service: input_number.set_value
        data:
          value: '{{ state_attr(target,''volume_level'') }}'
        target:
          entity_id: input_number.previous_volume
      - service: media_player.play_media
        target:
          entity_id: '{{target}}'
        data:
          media_content_id: http://192.168.207.101:8123/local/audio/awake.mp3
          media_content_type: music
          announce: true
      enabled: true
    - service: media_player.volume_set
      data:
        volume_level: 0.02
      target:
        entity_id: '{{target}}'
      enabled: true
    fields:
      target:
        selector:
          entity:
            filter:
            - integration: sonos
              domain: media_player
            multiple: false
        name: target
        description: The target speaker for which to set the volume.
        required: true
    mode: single
  'announce_jarvis_detection_end':
    alias: announce_jarvis_detection_end
    sequence:
    - service: media_player.volume_set
      data:
        volume_level: '{{states(''input_number.previous_volume'') | float}}'
      target:
        entity_id: '{{target}}'
    fields:
      target:
        selector:
          entity:
            filter:
            - integration: sonos
              domain: media_player
            multiple: false
        name: target
        description: The target speaker for which to set the volume.
        required: true
    mode: single
```
