### ISSUE TITLE
Poor end of speech detection

### ISSUE THREAD

**Issue by HarvsG** [rhasspy/wyoming-satellite#20]
I am running the satellite with local wake word detection on a raspberry pi 3 with an omnidirectional microphone and no speaker.
Wake words are detected almost instantly (I see the Assist In progress sensor change quickly). However for the light to actually turn off takes about 10 seconds (Assist In progress stays on for all of this time).
It seems to be that it is not detecting the end of speech well.
```yaml
stage: done
run:
  pipeline: 01gzv00ms6vap6j6fa7cn6t2s4
  language: en
events:
  - type: run-start
    data:
      pipeline: 01gzv00ms6vap6j6fa7cn6t2s4
      language: en
    timestamp: "2023-12-19T15:47:31.366949+00:00"
  - type: stt-start
    data:
      engine: cloud
      metadata:
        language: en-GB
        format: wav
        codec: pcm
        bit_rate: 16
        sample_rate: 16000
        channel: 1
    timestamp: "2023-12-19T15:47:31.367373+00:00"
  - type: stt-vad-end
    data:
      timestamp: 7500
    timestamp: "2023-12-19T15:47:46.339065+00:00"
  - type: stt-end
    data:
      stt_output:
        text: Turn on the study lamp.
    timestamp: "2023-12-19T15:47:46.593086+00:00"
  - type: intent-start
    data:
      engine: homeassistant
      language: en
      intent_input: Turn on the study lamp.
      conversation_id: null
      device_id: 87fd30dbb98112109029d1a8689bba24
    timestamp: "2023-12-19T15:47:46.593309+00:00"
  - type: intent-end
    data:
      intent_output:
        response:
          speech:
            plain:
              speech: Turned on light
              extra_data: null
          card: {}
          language: en
          response_type: action_done
          data:
            targets: []
            success:
              - name: Study Lamp
                type: entity
                id: light.study_lamp
            failed: []
        conversation_id: null
    timestamp: "2023-12-19T15:47:46.784007+00:00"
  - type: run-end
    data: null
    timestamp: "2023-12-19T15:47:46.784109+00:00"
stt:
  engine: cloud
  metadata:
    language: en-GB
    format: wav
    codec: pcm
    bit_rate: 16
    sample_rate: 16000
    channel: 1
  done: true
  stt_output:
    text: Turn on the study lamp.
intent:
  engine: homeassistant
  language: en
  intent_input: Turn on the study lamp.
  conversation_id: null
  device_id: 87fd30dbb98112109029d1a8689bba24
  done: true
  intent_output:
    response:
      speech:
        plain:
          speech: Turned on light
          extra_data: null
      card: {}
      language: en
      response_type: action_done
      data:
        targets: []
        success:
          - name: Study Lamp
            type: entity
            id: light.study_lamp
        failed: []
    conversation_id: null
```

journalctl produces no live output
```
george@redpi:~ $ journalctl -u wyoming-satellite.service -f
-- Journal begins at Tue 2023-12-05 06:31:03 GMT. --
Dec 19 15:41:32 redpi systemd[1]: Started Wyoming Satellite.
Dec 19 15:41:33 redpi run[624]: INFO:root:Ready
Dec 19 15:41:33 redpi run[624]: INFO:root:Connected to services
Dec 19 15:41:33 redpi run[633]: Recording raw data 'stdin' : Signed 16 bit Little Endian, Rate 16000 Hz, Mono
Dec 19 15:42:35 redpi run[624]: INFO:root:Waiting for wake word
Dec 19 15:42:55 redpi run[624]: INFO:root:Waiting for wake word
Dec 19 15:43:22 redpi run[624]: INFO:root:Waiting for wake word
Dec 19 15:44:38 redpi run[624]: INFO:root:Waiting for wake word
Dec 19 15:47:27 redpi run[624]: INFO:root:Waiting for wake word
Dec 19 15:47:46 redpi run[624]: INFO:root:Waiting for wake word
Dec 19 15:48:44 redpi run[624]: INFO:root:Waiting for wake word
```
```
george@redpi:~ $ journalctl -u wyoming-openwakeword.service -f
Dec 19 15:41:24 redpi systemd[1]: Started Wyoming openWakeWord.
Dec 19 15:41:29 redpi run[519]: INFO:root:Ready
Dec 19 15:41:34 redpi run[519]: INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
```

```ini
[Unit]
Description=Wyoming Satellite
Wants=network-online.target
After=network-online.target
Requires=wyoming-openwakeword.service

[Service]
Type=simple
ExecStart=/home/george/wyoming-satellite/script/run --name 'Study Satellite' --uri 'tcp://0.0.0.0:10400' --mic-command 'arecord -D plughw:CARD=Device,DEV=0 -r 16000 -c 1 -f S16_LE -t raw' --wake-word-name 'hey_rhasspy'
WorkingDirectory=/home/george/wyoming-satellite
Restart=always
RestartSec=1

[Install]
WantedBy=default.target
```

```ini
[Unit]
Description=Wyoming openWakeWord

[Service]
Type=simple
ExecStart=/home/george/wyoming-openwakeword/script/run --uri 'tcp://127.0.0.1:10400'
WorkingDirectory=/home/george/wyoming-openwakeword
Restart=always
RestartSec=1

[Install]
WantedBy=default.target
```
