### ISSUE TITLE
Satellite Mute Switch Not Working With On-Device Wake Word Detection

### ISSUE THREAD

**Issue by maxemoose** [rhasspy/wyoming-satellite#35]
I have a satellite set up in a room with a television. It is using on-device wake word detection. Even though the mute switch for the satellite is enabled in Home Assistant, sometimes chatter from the television will still trigger a false positive for the on-device wake word listener.

I added an automation in Home Assistant that monitors an Android TV device connected to the television. When media starts playing the satellite mute switch is enabled. When media stops/is paused/the device turns off then the satellite mute switch is disabled again. This automation is how I discovered this behaviour.

### Current Behavior:
Satellite mute switch is enabled in Home Assistant but on-device wake word detection still triggers.

### Expected Behavior:
Satellite mute switch is enabled in Home Assistant and on-device wake word detection stops.

### Steps To Reproduce:
1. Add alsa-utils to Dockerfile for rhasspy/wyoming-satellite before creating the Docker image. This enables the internal microphone and playback commands within the container.
2. Create openwake image 1.8.2 by [copying the following changes](https://github.com/rhasspy/wyoming-addons/pull/7/commits/cabfaa987008786dd4c6e0070867acc2b220d353). ~~(_side note - please update [Docker hub image](https://hub.docker.com/r/rhasspy/wyoming-openwakeword) to 1.8.2_)~~
3. Run this docker-compose.yml - make sure to change the hardware reference in the mic and snd commands.
```
version: "3.8"

services:
  WyomingOpenWakeWord:
    image: rhasspy/wyoming-openwakeword:1.8.2
    container_name: Wyoming-OpenWakeWord
    hostname: openwakeword
    restart: unless-stopped
    command:
      - "--preload-model"
      - "hey_jarvis"
      - "--uri"
      - "tcp://0.0.0.0:10400"
      - "--debug"
    ports:
      - 10400:10400

  WyomingSatellite:
    image: "rhasspy/wyoming-satellite"
    container_name: Wyoming-Satellite
    hostname: wyoming-satellite
    restart: unless-stopped
    ports:
      - "10700:10700"
    devices:
      - /dev/snd:/dev/snd
    command:
      - "--name"
      - "Voice Satellite"
      - "--area"
      - "Living Room"
      - "--uri"
      - "tcp://0.0.0.0:10700"
      # Internal Microphone and Playback
      - "--mic-command"
      - "arecord -D plughw:CARD=Snowball,DEV=0 -r 16000 -c 1 -f S16_LE -t raw"
      - "--snd-command"
      - "aplay -D plughw:CARD=Headphones,DEV=0 -r 22050 -c 1 -f S16_LE -t raw"
      # Local Wake Word Detection
      - "--wake-uri"
      - "tcp://openwakeword:10400"
      - "--wake-word-name"
      - "hey_jarvis"
      # Sounds
      - "--awake-wav"
      - "/customSounds/start_listening.wav"
      - "--done-wav"
      - "/customSounds/acknowledge.wav"
      - "--debug"
    volumes:
      - ./customSounds:/customSounds:ro
    depends_on:
      - WyomingOpenWakeWord
```

### Environment:
Raspberry Pi 4 B (4GB)
- OS: Ubuntu 22.04.3
- Docker: 24.0.7
- rhasspy/wyoming-satellite: latest (As of 31/12/2023)
- rhasspy/wyoming-openwakeword: 1.8.2
