### ISSUE TITLE
Error in mic_command process causes satellite to stop record sound without errors/recovery

### ISSUE THREAD

**Issue by allista** [rhasspy/wyoming-satellite#56]
Hi, I'm running wyoming-satellite in a docker container with VAD and webrtc, using host pulseaudio server via tcp to access the soundard (see docker-compose and Docker files below).

Everything works OK, but after some hours the `parecord` I use for `--mic-command` suddenly exits with a generic malloc error:

`Assertion 'size < (1024*1024*96)' failed at ../src/pulse/xmalloc.c:83, function pa_xrealloc(). Aborting.`

Nothing unusual :shrug:

The problem is that the satellite either dies without any log messages, or continues to run, but cannot record the sound anymore. In any case there are no more logs after this point.

---

`docker-compose.yaml`
```yaml
version: '3.8'
services:
  mic-satellite:
    container_name: mic-satellite
    image: wyoming-satellite-pa
    build:
      context: .
    command: |
      --mic-command 'parecord --device=no-echo-source --rate=16000 --channels=1 --format=s16le --raw'
      --snd-command 'paplay --volume=35000 --rate=22050 --channels=1 --format=s16le --raw --property=media.role=announce'
      --vad
      --mic-auto-gain 5
      --mic-noise-suppression 3
      --debug
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - PULSE_SERVER=host.docker.internal
```

`Dockerfile`
```Dockerfile
FROM rhasspy/wyoming-satellite

# Install PulseAudio utilities
RUN apt-get update && \
    apt-get install -y pulseaudio-utils && \
    rm -rf /var/lib/apt/lists/*

RUN .venv/bin/pip3 install 'pysilero-vad==1.0.0' 'webrtc-noise-gain==1.2.3'
```

`last logs`
```
mic-satellite  | INFO:root:Waiting for speech
mic-satellite  | INFO:root:Streaming audio
mic-satellite  | INFO:root:Waiting for speech
mic-satellite  | INFO:root:Streaming audio
mic-satellite  | INFO:root:Waiting for speech
mic-satellite  | INFO:root:Streaming audio
mic-satellite  | Assertion 'size < (1024*1024*96)' failed at ../src/pulse/xmalloc.c:83, function pa_xrealloc(). Aborting.

```
```
