### ISSUE TITLE
Issue with conversation_id Being None in extended_openai_conversation

### ISSUE THREAD

**Issue by LowKey88** [rhasspy/wyoming-satellite#95]
Refer Issue : https://github.com/jekalmin/extended_openai_conversation/issues/124

**Expected Behavior:**
Each `ConversationInput` instance should have a unique or continuous `conversation_id` that persists across related conversation inputs, enabling the tracking and management of ongoing conversations.

**Current Behavior:**
Debug logs indicate that every `ConversationInput` has a `conversation_id` of `None`. Here are some examples from the logs:

- `user_input: ConversationInput(text='xxx', context=<...>, conversation_id=None, device_id='...', language='*'), context: {'id': '...', 'parent_id': None, 'user_id': None}`
- `user_input: ConversationInput(text='xxx.', context=<...>, conversation_id=None, device_id='...', language='*'), context: {'id': '...', 'parent_id': None, 'user_id': None}`

**Comment by synesthesiam** [comment]
Thanks for bringing this to my attention! This will require some coordinated changes across HA and the satellite, but I'll get it in there :+1:

**Comment by PsY4** [comment]
That's a must have ! Nice to hear you work on this.

Will this help with the number of prompt_tokens sent in successive calls ? 
Maybe the "system" part of the prompt is not needed when conversation_id is set ...

**Comment by llluis** [comment]
> Thanks for bringing this to my attention! This will require some coordinated changes across HA and the satellite, but I'll get it in there 👍

Would that be adding a new attribute in all events to hold the id? (And modify both ends to use it)

**Comment by synesthesiam** [comment]
I will add the conversation id to the "context" field that several Wyoming messages already have.

The only question is when/if to reset the id after some period of inactivity. ESPHome does this after 5 minutes.

**Comment by synesthesiam** [comment]
> That's a must have ! Nice to hear you work on this.
> 
> Will this help with the number of prompt_tokens sent in successive calls ? 
> Maybe the "system" part of the prompt is not needed when conversation_id is set ...

This will just tell the integration the key to look up the context. It's up to the integration to decide what to keep or discard before sending it to the LLM.

**Comment by Edmundas1** [comment]
> I will add the conversation id to the "context" field that several Wyoming messages already have.
> 
> The only question is when/if to reset the id after some period of inactivity. ESPHome does this after 5 minutes.

If integrations decide on what should be included in context to send to LLMs based on conversation id, then it should be reset and 5 minutes (or configurable if not hard to implement) looks ok, otherwise context size will grow huge and we'll run out of tokens. :)

**Comment by eponce92** [comment]
this would be great ! I'm using Extended OpenAI Conversation with gpt 3.5 and it's just amaizing. Its what we thought alexa and google assistant will be eventually but never got to be. It works great on the phone but I miss not beeing able to do a follow up question on the satelite I have in the kitchen.

**Comment by emanuelbaltaretu** [comment]
I have come here for the same reason, assistant often asks questions like this light or the one from the kitchen, or found this music, what shall i play? but when i respond of course it's a new convo for it. 
Any new update on this?

**Comment by kbromer** [comment]
Chiming in here - this would be a great addition to have available, regardless of if you're using the OpenAI extension or something else non-ESP!

**Comment by eponce92** [comment]
Hi @synesthesiam, could you please give us any insight on whether we should switch to ESP32-based hardware instead of using a Raspberry Pi? Seeing all the official development going towards ESP32-based hardware lately, I wanted to know if this is going to be the future of voice assistant hardware and if the Pi option won't be supported any longer?

**Comment by synesthesiam** [comment]
Both the ESP and Pi options will continue to be supported. The difference is that there are now 4 people (including me) working on voice in ESPHome and only one (again me) working on Wyoming satellites 😄

I've been slowly getting PR's merged and new features added. The conversation id is on my list for this upcoming week 👍

**Comment by eponce92** [comment]
Thanks for the update! I'll keep the Pi satelites then. This project is great! Appreciate the hard work and looking forward to the new features.

**Comment by synesthesiam** [comment]
As part of the upcoming release, I have added this: https://github.com/home-assistant/core/pull/118835
Conversation id is automatically generated and kept for 5 minutes of inactivity within HA.

**Comment by holzmichlnator** [comment]
Really love to see this change, thanks a lot <3. Is this also available for the ESPHome/ESP32 satellites?

**Comment by synesthesiam** [comment]
Yes, this has been a part of the ESPHome voice assistant for a few releases now. They have the 5 minute timeout as well.

**Comment by breinsp** [comment]
Is this change included in the current version (2024.7.2)?

**Comment by guinmoon** [comment]
Hi. Can you tell me if I'm doing this right? 
I have `wyoming-satellite` configured on one device in docker and `home assistant` with `extended_openai_conversation` on another.
Every time openWakeWord is triggered `wyoming-satellite` listens to the microphone and extended_openai_conversation responds, but after the response the dialog ends.
Besides, debugging shows that `conversation_id` is different every time. 

My docker-compose:
```YAML
ersion: '3.0'

services:

  satellite:
    container_name: wyoming-satellite
    build: https://github.com/rhasspy/wyoming-satellite.git
    image: rhasspy/wyoming-satellite   
    restart: unless-stopped    
    volumes:
      - ./wyoming-satellite/sounds:/sounds
      - ~/.config/pulse:/root/.config/pulse
    ports:
      - "10700:10700"
    command:    
      - "--debug"
      - "--name"
      - "living_room"
      - "--uri"
      - "tcp://0.0.0.0:10700"
      - "--mic-uri"
      - "tcp://microphone:10600"
      - "--snd-command"
      - "aplay --device \"pulse\" -r 22050 -c 1 -f S16_LE -t raw"
      - "--awake-wav"
      - "/sounds/act1.wav"
      - "--done-wav"
      - "/sounds/act2.wav"
    environment:
      - "PULSE_SERVER=host.docker.internal"

 playback:
    container_name: wyoming-snd-external
    build: https://github.com/guinmoon/wyoming-snd-external-pulse.git
    image: wyoming-snd-external:pulse
    restart: unless-stopped
    volumes:
      - ~/.config/pulse:/root/.config/pulse
    ports:
      - "10601:10601"    
    command: 
      - "--debug"      
      - "--device"
      - "pulse"            
    environment:
      - "PULSE_SERVER=host.docker.internal"

  microphone:
    container_name: wyoming-mic-external
    build: https://github.com/guinmoon/wyoming-mic-external-pulse.git
    image: wyoming-mic-external-pulse
    restart: unless-stopped    
    volumes:
      - ~/.config/pulse:/root/.config/pulse
    ports:
      - "10600:10600"
    command:
      - "--device"
      - "pulse"  
      - "--debug"
    environment:
      - "PULSE_SERVER=host.docker.internal"

  openwakeword:
    container_name: openwakeword
    image: guinmoon/wyoming-openwakeword
    volumes:
      - ~/.config/pulse:/root/.config/pulse    
      - ./openWakeWord/data:/data
      - ./openWakeWord/custom:/custom
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro      
    ports:
      - "10400:10400"
    command: 
      --preload-model 'alexa'
      --custom-model-dir /custom
      --model 'alexa'      
      --uri 'tcp://0.0.0.0:10400'
      --debug
    restart: unless-stopped 
    environment:
      - TZ=Europe/Moscow
      - "PULSE_SERVER=host.docker.internal"  
```
