### ISSUE TITLE
homeassistant_satellite_event Equivalent

### ISSUE THREAD

**Issue by nubicula** [rhasspy/wyoming-satellite#96]
Apologies for misunderstandings here, but with the previous homeassistant satellite, I was able to use homeasisstant-satellite-event to perform this automation. What would be the equivalent way to redirect TTS from satellite and to another media entity, because for me the above event no longer fires, although the satellite acts as expected (LED Ring, and intents are fired)
alias: "VoiceSatellite: Redirect Audio"
description: ""
trigger:
  - platform: event
    event_type: homeassistant_satellite_event
    event_data:
      satellite_name: LoungeVA
condition:
  - condition: template
    value_template: "{{ trigger.event.data.pipeline_event.type == 'tts-end' }}"
    enabled: true
action:
  - service: media_player.play_media
    data:
      announce: true
      media_content_type: music
      media_content_id: "{{ trigger.event.data.pipeline_event.data.tts_output.media_id }}"
    target:
      entity_id: media_player.sonos_beam
mode: parallel
max: 10

**Comment by llluis** [comment]
Right now, this function is not available. 

The current version of the wyoming-satellite does not generate any event in Home Assistant (a standard event), so, your trigger will never fire (as you found out).

**Comment by llluis** [comment]
OK, I was just able to implement this in the current version:

```
event_type: wyoming-satellite
data:
  satellite_name: unknown
  pipeline_event:
    type: tts-end
    data:
      tts_output:
        media_id: >-
          media-source://tts/cloud?message=Tudo+%C3%B3timo+por+aqui.+Posso+ajudar+com+alguma+coisa?&language=pt-BR&voice=AntonioNeural&preferred_format=wav&preferred_sample_rate=16000&preferred_sample_channels=1
        url: >-
          /api/tts_proxy/9bf0ebc456c23763b64b2178e95c95aff21a71fd_pt-br_9ffd1ac079_cloud.wav
        mime_type: audio/x-wav
origin: LOCAL
time_fired: "2024-01-30T21:19:45.623216+00:00"
context:
  id: 01HNE3W1YQ9SFCXKDHCE16RKZG
  parent_id: null
  user_id: null
```

@synesthesiam, right now we just convert pipeline events in wyoming events.
Do we have the interest in firing HA bus events from those pipeline events, the same way you did with homeassistant-satellite? I could send a PR for the wyoming integration (didn't looked for the satellite_name yet):
```
        # Fires event in Home Assistant bus
        event_data = {
            "satellite_name": "unknown",
            "pipeline_event": {
                "type": event.type,
                "data": event.data,
            },
        }
        self.hass.bus.fire("wyoming-satellite", event_data)
```
